// <auto-generated/>
// Gerador para auxiliar na localização de arquivos SQL.
// Os códigos deste arquivo serão compilados.

using System;
using SqlAsFile;
namespace Sample.Data
{
    namespace SampleNamespace1
    {
        namespace SampleSubNamespace1
        {
            public static class Sql
            {
                private static readonly Lazy<FileSqlInfo> _SampleSql2 = new Lazy<FileSqlInfo>(() => new FileSqlInfo("SampleNamespace1/SampleSubNamespace1/SampleSql2.sql"));

                /// <summary>
                /// Informações do comando SQL existente no arquivo SampleNamespace1/SampleSubNamespace1/SampleSql2.sql.
                /// </summary>
                public static FileSqlInfo SampleSql2 => _SampleSql2.Value;


            }

        }
        public static class Sql
        {
            private static readonly Lazy<FileSqlInfo> _SampleSql1 = new Lazy<FileSqlInfo>(() => new FileSqlInfo("SampleNamespace1/SampleSql1.sql"));

            /// <summary>
            /// Informações do comando SQL existente no arquivo SampleNamespace1/SampleSql1.sql.
            /// </summary>
            public static FileSqlInfo SampleSql1 => _SampleSql1.Value;


        }

    }
    namespace SampleNamespace2
    {
        public static class Sql
        {
            private static readonly Lazy<FileSqlInfo> _SampleSql3 = new Lazy<FileSqlInfo>(() => new FileSqlInfo("SampleNamespace2/SampleSql3.sql"));

            /// <summary>
            /// Informações do comando SQL existente no arquivo SampleNamespace2/SampleSql3.sql.
            /// </summary>
            public static FileSqlInfo SampleSql3 => _SampleSql3.Value;


        }

    }

}
